# Generated by Django 4.1.6 on 2023-03-08 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clients_customuser_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='users',
            field=models.ManyToManyField(related_name='teammate', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
    ]
