# Generated by Django 4.1.6 on 2023-06-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_clients_created_at_clients_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagsForApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitstructure.appobjet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('structure', models.JSONField(verbose_name='структура данных')),
                ('table_name', models.CharField(max_length=120, verbose_name='название таблицы в БД')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitstructure.appobjet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiOfApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('prefix', models.CharField(max_length=50, verbose_name='префикс в url')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitstructure.appobjet')),
                ('tags', models.ManyToManyField(to='kitstructure.tagsforapi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
