# Generated by Django 4.1.6 on 2023-08-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitstructure', '0002_alter_apiofapp_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='appobjet',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appobjet',
            name='db_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
