name: CI deploy Python service to server
on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "DB_NAME=${{ secrets.DB_NAME }}"
            "PROD=True"
            "DB_USER=${{ secrets.DB_USER }}"
            "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
            "API_KIT_SERVICE=${{ vars.API_KIT_SERVICE }}"
            "DB_HOST=${{ vars.DB_HOST }}"
            "HOST=${{ vars.HOST }}"
            "HOSTNAME=${{ vars.HOSTNAME }}"
            "DB_PORT=${{ secrets.DB_PORT }}"
          push: true
          tags: chitsalex/europlumbing:latest
